// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Sun Aug 13 06:28:49 2023

FA FA_inst
(
	.sum(sum_sig) ,	// output  sum_sig
	.cout(cout_sig) ,	// output  cout_sig
	.c1(c1_sig) ,	// output  c1_sig
	.c2(c2_sig) ,	// output  c2_sig
	.a(a_sig) ,	// input  a_sig
	.b(b_sig) ,	// input  b_sig
	.cin(cin_sig) 	// input  cin_sig
);

